In [1]:
import requests as req
import pandas as pd
from bs4 import BeautifulSoup as bs

# pd.set_option("display.max_columns", None)
# pd.set_option("display.max_rows", None)
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}

In [2]:
leagueTables = [
    "https://www.transfermarkt.com/premier-league/tabelle/wettbewerb/GB1/saison_id/2024",
    "https://www.transfermarkt.com/laliga/tabelle/wettbewerb/ES1/saison_id/2024",
    "https://www.transfermarkt.com/ligue-1/tabelle/wettbewerb/FR1/saison_id/2024",
    "https://www.transfermarkt.com/bundesliga/tabelle/wettbewerb/L1/saison_id/2024",
    "https://www.transfermarkt.com/serie-a/tabelle/wettbewerb/IT1/saison_id/2024",
]

listClub = pd.DataFrame()
for link in leagueTables:
    re = req.get(link, headers=headers)
    so = bs(re.content, "html.parser")
    tb = so.select_one('table:contains("Goals")')
    innerListClub = pd.DataFrame(
        {
            "Mini Team Crest": [
                (i["src"]) for i in tb.select("tbody td:nth-of-type(2) a img")
            ],
            "Team": [(i["title"]) for i in tb.select("tbody td:nth-of-type(2) a img")],
            "Team Link": [
                ("https://www.transfermarkt.com" + i["href"] + "/plus/1")
                for i in tb.select("tbody td:nth-of-type(3) a:nth-of-type(1)")
            ],
            "MP": [(i.text) for i in tb.select("tbody td:nth-of-type(4)")],
            "W": [(i.text) for i in tb.select("tbody td:nth-of-type(5)")],
            "D": [(i.text) for i in tb.select("tbody td:nth-of-type(6)")],
            "L": [(i.text) for i in tb.select("tbody td:nth-of-type(7)")],
            "Goals": [(i.text) for i in tb.select("tbody td:nth-of-type(8)")],
            "+/-": [(i.text) for i in tb.select("tbody td:nth-of-type(9)")],
            "Pts": [(i.text) for i in tb.select("tbody td:nth-of-type(10)")],
        }
    )

    def decideLeague(x):
        if link == leagueTables[0]:
            x = "EPL"
            return x
        elif link == leagueTables[1]:
            x = "La Liga"
            return x
        elif link == leagueTables[2]:
            x = "Ligue 1"
            return x
        elif link == leagueTables[3]:
            x = "Bundesliga"
            return x
        elif link == leagueTables[4]:
            x = "Serie A"
            return x

    innerListClub["League"] = innerListClub.apply(decideLeague, axis=1)

    listClub = pd.concat([listClub, innerListClub], axis=0)


def clubCrestBig(x):
    return x["Mini Team Crest"].replace("tiny", "head")


listClub["Big Team Crest"] = listClub.apply(clubCrestBig, axis=1)
listClub.insert(1, "Big Team Crest", listClub.pop("Big Team Crest"))


def teamLink(x):
    return x["Team Link"].replace("/spielplan/", "/kader/")


listClub["Team Link"] = listClub.apply(teamLink, axis=1)


def teamLinkSecondFirst(x):
    return x["Team Link"].replace("/kader/", "/leistungsdaten/")


listClub["Team Link 2"] = listClub.apply(teamLinkSecondFirst, axis=1)


def teamLinkSecondSecond(x):
    if x["League"] == "EPL":
        return x["Team Link 2"].replace("/saison_id/2024/", "/reldata/GB1%262024/")
    elif x["League"] == "La Liga":
        return x["Team Link 2"].replace("/saison_id/2024/", "/reldata/ES1%262024/")
    elif x["League"] == "Ligue 1":
        return x["Team Link 2"].replace("/saison_id/2024/", "/reldata/FR1%262024/")
    elif x["League"] == "Bundesliga":
        return x["Team Link 2"].replace("/saison_id/2024/", "/reldata/L1%262024/")
    elif x["League"] == "Serie A":
        return x["Team Link 2"].replace("/saison_id/2024/", "/reldata/IT1%262024/")


listClub["Team Link 2"] = listClub.apply(teamLinkSecondSecond, axis=1)


listClub["Pts/MP"] = listClub["Pts"].astype(int) / listClub["MP"].astype(int)
listClub["Pts/MP"] = listClub["Pts/MP"].round(2)
listClubDetails = listClub.sort_values(by="Team", ascending=True)
finalListClub = listClubDetails.reset_index(drop=True)

finalListClub

c:\Users\Hp\Web Development\Portfolio\The-Score\venv\Lib\site-packages\soupsieve\css_parser.py:862: FutureWarning: The pseudo class ':contains' is deprecated, ':-soup-contains' should be used moving forward.
  warnings.warn(  # noqa: B028

,Mini Team Crest,Big Team Crest,Team,Team Link,MP,W,D,L,Goals,+/-,Pts,League,Team Link 2,Pts/MP
0,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,1.FC Heidenheim 1846,https://www.transfermarkt.com/1-fc-heidenheim-...,18,4,2,12,23:38,-15,14,Bundesliga,https://www.transfermarkt.com/1-fc-heidenheim-...,0.78
1,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,1.FC Union Berlin,https://www.transfermarkt.com/1-fc-union-berli...,18,5,4,9,15:25,-10,19,Bundesliga,https://www.transfermarkt.com/1-fc-union-berli...,1.06
2,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,1.FSV Mainz 05,https://www.transfermarkt.com/1-fsv-mainz-05/k...,18,8,4,6,31:23,8,28,Bundesliga,https://www.transfermarkt.com/1-fsv-mainz-05/l...,1.56
3,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,AC Milan,https://www.transfermarkt.com/ac-mailand/kader...,20,8,7,5,29:21,8,31,Serie A,https://www.transfermarkt.com/ac-mailand/leist...,1.55
4,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,AC Monza,https://www.transfermarkt.com/ac-monza/kader/v...,21,2,7,12,20:31,-11,13,Serie A,https://www.transfermarkt.com/ac-monza/leistun...,0.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,VfL Bochum,https://www.transfermarkt.com/vfl-bochum/kader...,18,3,3,12,18:39,-21,12,Bundesliga,https://www.transfermarkt.com/vfl-bochum/leist...,0.67
92,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,VfL Wolfsburg,https://www.transfermarkt.com/vfl-wolfsburg/ka...,18,8,3,7,40:32,8,27,Bundesliga,https://www.transfermarkt.com/vfl-wolfsburg/le...,1.50
93,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,Villarreal CF,https://www.transfermarkt.com/fc-villarreal/ka...,20,9,6,5,38:31,7,33,La Liga,https://www.transfermarkt.com/fc-villarreal/le...,1.65
94,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,West Ham United,https://www.transfermarkt.com/west-ham-united/...,22,7,5,10,27:43,-16,26,EPL,https://www.transfermarkt.com/west-ham-united/...,1.18
95,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,Wolverhampton Wanderers,https://www.transfermarkt.com/wolverhampton-wa...,22,4,4,14,32:51,-19,16,EPL,https://www.transfermarkt.com/wolverhampton-wa...,0.73

In [3]:
listPlayer = pd.DataFrame()
for l in finalListClub["Team Link"]:
    r = req.get(
        l,
        headers=headers,
    )
    s = bs(r.content, "html.parser")
    t = s.find("table", class_="items")
    rows = s.select("tbody tr")
    
    innerListPlayer = pd.DataFrame(
        {
            "Player": [(i["title"]) for i in t.select("tbody td:nth-of-type(1) img")],
            "Position": [
                (i.text)
                for i in t.select("tbody td:nth-of-type(2) tr td:nth-of-type(1)")
            ][1::2],
            "Age": [(i.text) for i in t.select("tbody td:nth-of-type(3)")],
            "Height": [(i.text) for i in t.select("tbody td:nth-of-type(5)")],
            "Foot": [(i.text) for i in t.select("tbody td:nth-of-type(6)")],
            "Market Value": [(i.text) for i in t.select("tbody .rechts.hauptlink")],
        }
    )

    dataNation = [[td["title"].strip() for td in row.select("td:nth-of-type(4) img")] for row in rows]
    filteredDataNation = [sublist for sublist in dataNation if sublist]
    dataNationFlag = [[td["src"].strip() for td in row.select("td:nth-of-type(4) img")] for row in rows]
    filteredDataNationFlag = [sublist for sublist in dataNationFlag if sublist]

    filteredDataNationList = []
    for i in filteredDataNation:
        filteredDataNationList.append(i[0])

    filteredDataNationFlagList = []
    for i in filteredDataNationFlag:
        filteredDataNationFlagList.append(i[0])

    innerListPlayer["Nation"] = filteredDataNationList
    innerListPlayer["Nation Flag Link"] = filteredDataNationFlagList

    teams = s.find_all(
        class_="data-header__headline-wrapper data-header__headline-wrapper--oswald"
    )
    teamName = [team.get_text(strip=True) for team in teams]

    def addTeamName(c):
        c = teamName[0]
        return c

    innerListPlayer["Team"] = innerListPlayer.apply(addTeamName, axis=1)

    listPlayer = pd.concat([listPlayer, innerListPlayer], axis=0)

listPlayer["Age"] = listPlayer["Age"].str[-3:-1]
listPlayer["Position"] = listPlayer["Position"].replace("\n", "", regex=True)
listPlayer["Position"] = listPlayer["Position"].str.strip()
listPlayer.index = range(0, len(listPlayer))

listPlayer

,Player,Position,Age,Height,Foot,Market Value,Nation,Nation Flag Link,Team
0,Kevin Müller,Goalkeeper,33,"1,90m",right,€1.00m,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846
1,Frank Feller,Goalkeeper,21,"1,83m",right,€350k,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846
2,Vitus Eicher,Goalkeeper,34,"1,91m",left,€250k,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846
3,Paul Tschernuth,Goalkeeper,23,"1,86m",left,€100k,Austria,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846
4,Benedikt Gimber,Centre-Back,27,"1,87m",left,€3.00m,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846
...,...,...,...,...,...,...,...,...,...
2623,Matheus Cunha,Centre-Forward,25,"1,83m",right,€50.00m,Brazil,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers
2624,Jørgen Strand Larsen,Centre-Forward,24,"1,93m",right,€27.00m,Norway,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers
2625,Hee-chan Hwang,Centre-Forward,28,"1,77m",right,€22.00m,"Korea, South",https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers
2626,Sasa Kalajdzic,Centre-Forward,27,"2,00m",right,€5.00m,Austria,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers
2627,Nathan Fraser,Centre-Forward,19,"1,88m",right,€600k,Ireland,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers

In [4]:
marketValueOne = listPlayer[listPlayer["Market Value"].str.contains("k")]
listPlayer.drop(
    listPlayer[listPlayer["Market Value"].str.contains("k")].index,
    inplace=True,
)

marketValueSecond = marketValueOne[
    marketValueOne["Market Value"].str.contains("\xa0\xa0")
]
marketValueOne.drop(
    marketValueOne[marketValueOne["Market Value"].str.contains("\xa0\xa0")].index,
    inplace=True,
)

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\3745614528.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marketValueOne.drop(

In [5]:
marketValueSeventh = pd.DataFrame()
marketValueSeventh["Market Value"] = marketValueOne["Market Value"].str[1:-1]
marketValueSeventh["Market Value"] = pd.to_numeric(marketValueSeventh["Market Value"])

marketValueSeventh

      Market Value
1              350
2              250
3              100
7              300
15             200
...            ...
2574           700
2580           700
2599           200
2618           500
2627           600

[388 rows x 1 columns]

In [6]:
valueList = []
for value in marketValueSeventh["Market Value"]:
    if value < 100 and value > 0:
        value = 0.1
        valueList.append(value)
    else:
        value = round((value / 1000), 1)
        valueList.append(value)

valueList

[0.3,
 0.2,
 0.1,
 0.3,
 0.2,
 0.2,
 0.5,
 0.7,
 0.3,
 0.2,
 0.6,
 0.1,
 0.3,
 0.2,
 0.8,
 0.8,
 0.8,
 0.7,
 0.5,
 0.8,
 0.1,
 0.8,
 0.5,
 0.3,
 0.7,
 0.6,
 0.3,
 0.5,
 0.1,
 0.1,
 0.5,
 0.1,
 0.8,
 0.1,
 0.2,
 0.2,
 0.5,
 0.3,
 0.1,
 0.8,
 0.5,
 0.9,
 0.8,
 0.3,
 0.7,
 0.8,
 0.8,
 0.1,
 0.5,
 0.3,
 0.8,
 0.3,
 0.7,
 0.2,
 0.3,
 0.8,
 0.4,
 0.2,
 0.6,
 0.7,
 0.5,
 0.5,
 0.1,
 0.5,
 0.5,
 0.2,
 0.8,
 0.5,
 0.5,
 0.2,
 0.4,
 0.9,
 0.8,
 0.2,
 0.4,
 0.3,
 0.5,
 0.8,
 0.3,
 0.8,
 0.4,
 0.9,
 0.6,
 0.3,
 0.3,
 0.8,
 0.1,
 0.8,
 0.4,
 0.1,
 0.7,
 0.8,
 0.7,
 0.8,
 0.9,
 0.9,
 0.8,
 0.7,
 0.6,
 0.1,
 0.1,
 0.2,
 0.6,
 0.4,
 0.2,
 0.4,
 0.4,
 0.3,
 0.5,
 0.5,
 0.9,
 0.2,
 0.1,
 0.1,
 0.5,
 0.1,
 0.4,
 0.9,
 0.2,
 0.3,
 0.8,
 0.3,
 0.5,
 0.5,
 0.5,
 0.1,
 0.5,
 0.1,
 0.8,
 0.2,
 0.9,
 0.5,
 0.2,
 0.8,
 0.7,
 0.5,
 0.8,
 0.1,
 0.5,
 0.1,
 0.5,
 0.3,
 0.2,
 0.1,
 0.6,
 0.1,
 0.9,
 0.6,
 0.2,
 0.7,
 0.5,
 0.5,
 0.3,
 0.3,
 0.3,
 0.2,
 0.5,
 0.1,
 0.8,
 0.7,
 0.8,
 0.2,
 0.6,
 0.8,
 0.2,
 0.1,
 0.6,
 0.8,
 0.6,
 0.5,
 0.8,
 0.8,
 0.7,
 0.4,
 0.2,
 0.2,
 0.1,
 0.9,
 0.2,
 0.1,
 0.9,
 0.8,
 0.1,
 0.8,
 0.5,
 0.4,
 0.1,
 0.4,
 0.2,
 0.1,
 0.8,
 0.7,
 0.7,
 0.6,
 0.5,
 0.7,
 0.5,
 0.1,
 0.8,
 0.8,
 0.3,
 0.9,
 0.3,
 0.9,
 0.5,
 0.2,
 0.2,
 0.1,
 0.2,
 0.1,
 0.6,
 0.8,
 0.6,
 0.2,
 0.1,
 0.7,
 0.9,
 0.6,
 0.5,
 0.4,
 0.9,
 0.5,
 0.2,
 0.2,
 0.9,
 0.1,
 0.4,
 0.9,
 0.8,
 0.4,
 0.8,
 0.3,
 0.2,
 0.2,
 0.3,
 0.1,
 0.5,
 0.3,
 0.3,
 0.5,
 0.8,
 0.1,
 0.5,
 0.3,
 0.2,
 0.5,
 0.3,
 0.4,
 0.3,
 0.1,
 0.1,
 0.4,
 0.8,
 0.8,
 0.1,
 0.8,
 0.3,
 0.9,
 0.3,
 0.9,
 0.2,
 0.3,
 0.2,
 0.9,
 0.4,
 0.3,
 0.1,
 0.8,
 0.9,
 0.9,
 0.3,
 0.5,
 0.5,
 0.4,
 0.9,
 0.8,
 0.8,
 0.6,
 0.8,
 0.5,
 0.2,
 0.3,
 0.8,
 0.8,
 0.9,
 0.5,
 0.5,
 0.6,
 0.4,
 0.8,
 0.7,
 0.8,
 0.1,
 0.1,
 0.5,
 0.2,
 0.2,
 0.4,
 0.1,
 0.3,
 0.6,
 0.5,
 0.3,
 0.6,
 0.5,
 0.8,
 0.9,
 0.3,
 0.4,
 0.5,
 0.8,
 0.3,
 0.1,
 0.5,
 0.8,
 0.2,
 0.7,
 0.1,
 0.1,
 0.3,
 0.1,
 0.8,
 0.5,
 0.5,
 0.3,
 0.8,
 0.4,
 0.6,
 0.5,
 0.9,
 0.7,
 0.8,
 0.8,
 0.1,
 0.1,
 0.2,
 0.1,
 0.8,
 0.1,
 0.8,
 0.4,
 0.7,
 0.3,
 0.1,
 0.1,
 0.5,
 0.2,
 0.6,
 0.5,
 0.8,
 0.1,
 0.9,
 0.9,
 0.2,
 0.8,
 0.7,
 0.6,
 0.3,
 0.4,
 0.5,
 0.5,
 0.6,
 0.5,
 0.5,
 0.3,
 0.1,
 0.6,
 0.2,
 0.5,
 0.5,
 0.2,
 0.6,
 0.7,
 0.8,
 0.3,
 0.1,
 0.6,
 0.5,
 0.8,
 0.8,
 0.5,
 0.5,
 0.9,
 0.7,
 0.7,
 0.2,
 0.5,
 0.6]

In [7]:
marketValueSeventh["Market Value"] = valueList
marketValueSeventh

      Market Value
1              0.3
2              0.2
3              0.1
7              0.3
15             0.2
...            ...
2574           0.7
2580           0.7
2599           0.2
2618           0.5
2627           0.6

[388 rows x 1 columns]

In [8]:
marketValueEighth = pd.DataFrame()
marketValueEighth["Market Value"] = marketValueSecond["Market Value"].str[1:-3]
marketValueEighth["Market Value"] = pd.to_numeric(marketValueEighth["Market Value"])

marketValueEighth

    Market Value
65           150

In [9]:
otherValueList = []
for v in marketValueEighth["Market Value"]:
    if v < 100 and v > 0:
        v = 0.1
        otherValueList.append(v)
    else:
        v = round((v / 1000), 1)
        otherValueList.append(v)

otherValueList

[0.1]

In [10]:
marketValueEighth["Market Value"] = otherValueList
marketValueEighth

    Market Value
65           0.1

In [11]:
marketValueOne.drop(columns=["Market Value"], inplace=True)
marketValueSecond.drop(columns=["Market Value"], inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2085958102.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marketValueOne.drop(columns=["Market Value"], inplace=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2085958102.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marketValueSecond.drop(columns=["Market Value"], inplace=True)

In [12]:
marketValueThird = pd.concat([marketValueOne, marketValueSeventh], axis=1)
marketValueNinth = pd.concat([marketValueSecond, marketValueEighth], axis=1)

marketValueTenth = pd.concat([marketValueThird, marketValueNinth], axis=0)

In [13]:
marketValueTenth

,Player,Position,Age,Height,Foot,Nation,Nation Flag Link,Team,Market Value
1,Frank Feller,Goalkeeper,21,"1,83m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.3
2,Vitus Eicher,Goalkeeper,34,"1,91m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.2
3,Paul Tschernuth,Goalkeeper,23,"1,86m",left,Austria,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.1
7,Thomas Keller,Centre-Back,25,"1,86m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.3
15,Luka Janes,Defensive Midfield,21,"1,83m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.2
...,...,...,...,...,...,...,...,...,...
2580,Aaron Cresswell,Left-Back,35,"1,70m",left,England,https://tmssl.akamaized.net//images/flagge/ver...,West Ham United,0.7
2599,Tom King,Goalkeeper,29,"1,94m",right,Wales,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,0.2
2618,Tawanda Chirewa,Attacking Midfield,21,"1,81m",right,Zimbabwe,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,0.5
2627,Nathan Fraser,Centre-Forward,19,"1,88m",right,Ireland,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,0.6
65,Maxim Dal,Centre-Back,18,"1,88m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FSV Mainz 05,0.1

In [14]:
marketValueFourth = listPlayer[listPlayer["Market Value"].str.contains("m")]
listPlayer.drop(
    listPlayer[listPlayer["Market Value"].str.contains("m")].index,
    inplace=True,
)

marketValueFifth = marketValueFourth[marketValueFourth["Market Value"].str.contains("\xa0\xa0")]
marketValueFourth.drop(
    marketValueFourth[marketValueFourth["Market Value"].str.contains("\xa0\xa0")].index,
    inplace=True,
)

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2434364806.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marketValueFourth.drop(

In [15]:
listPlayer["Market Value"] = 0.0
listPlayer.insert(4, "Market Value", listPlayer.pop("Market Value"))

In [16]:
listPlayer

,Player,Position,Age,Height,Market Value,Foot,Nation,Nation Flag Link,Team
23,Christopher Negele,Left Winger,19,"1,72m",0.0,right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846
37,Oluwaseun Ogbemudia,Centre-Back,18,"1,85m",0.0,right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Union Berlin
174,Owen Bevan,Centre-Back,21,"1,86m",0.0,,Wales,https://tmssl.akamaized.net//images/flagge/ver...,AFC Bournemouth
195,Tom Negrel,Goalkeeper,21,"1,92m",0.0,right,France,https://tmssl.akamaized.net//images/flagge/ver...,AJ Auxerre
211,Ben Viadere,Attacking Midfield,19,"1,76m",0.0,right,France,https://tmssl.akamaized.net//images/flagge/ver...,AJ Auxerre
298,Oumar Pona,Goalkeeper,18,"1,89m",0.0,right,France,https://tmssl.akamaized.net//images/flagge/ver...,Angers SCO
451,Luca Novodomsky,Goalkeeper,19,-,0.0,,Germany,https://tmssl.akamaized.net//images/flagge/ver...,Bayer 04 Leverkusen
463,Matija Marsenic,Central Midfield,20,"1,79m",0.0,both,Montenegro,https://tmssl.akamaized.net//images/flagge/ver...,Bayer 04 Leverkusen
565,Niklas Swider,Defensive Midfield,18,"1,88m",0.0,right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,Borussia Mönchengladbach
610,Killian Cahill,Goalkeeper,21,-,0.0,right,Ireland,https://tmssl.akamaized.net//images/flagge/ver...,Brighton & Hove Albion
762,Tyrique George,Left Winger,18,"1,81m",0.0,right,England,https://tmssl.akamaized.net//images/flagge/ver...,Chelsea FC
817,Caleb Kporha,Right-Back,18,-,0.0,right,England,https://tmssl.akamaized.net//images/flagge/ver...,Crystal Palace
1062,Ylies Aradj,Left-Back,19,"1,79m",0.0,left,France,https://tmssl.akamaized.net//images/flagge/ver...,FC Toulouse
1171,Selvi Clua,Central Midfield,19,"1,89m",0.0,left,Spain,https://tmssl.akamaized.net//images/flagge/ver...,Girona FC
1176,Min-su Kim,Left Winger,19,"1,77m",0.0,right,"Korea, South",https://tmssl.akamaized.net//images/flagge/ver...,Girona FC
1378,Ruben Londja,Right Winger,18,-,0.0,,Switzerland,https://tmssl.akamaized.net//images/flagge/ver...,Le Havre AC
1404,Will Alves,Attacking Midfield,19,-,0.0,right,England,https://tmssl.akamaized.net//images/flagge/ver...,Leicester City
1477,Harry Amass,Left-Back,17,"1,81m",0.0,left,England,https://tmssl.akamaized.net//images/flagge/ver...,Manchester United
1494,Ethan Wheatley,Centre-Forward,19,"1,87m",0.0,,England,https://tmssl.akamaized.net//images/flagge/ver...,Manchester United
1521,Glenn Ngosso,Centre-Forward,21,-,0.0,,Cameroon,https://tmssl.akamaized.net//images/flagge/ver...,Montpellier HSC
1651,Gaël Lafont,Central Midfield,18,"1,75m",0.0,left,France,https://tmssl.akamaized.net//images/flagge/ver...,Olympique Marseille
1654,Darryl Bakola,Attacking Midfield,17,"1,78m",0.0,right,France,https://tmssl.akamaized.net//images/flagge/ver...,Olympique Marseille
1658,Keyliane Abdallah,Right Winger,18,"1,85m",0.0,left,France,https://tmssl.akamaized.net//images/flagge/ver...,Olympique Marseille
1749,Ismaëlo Ganiou,Centre-Back,19,"1,85m",0.0,right,France,https://tmssl.akamaized.net//images/flagge/ver...,RC Lens
1789,Tidiane Diallo,Attacking Midfield,18,"1,76m",0.0,right,France,https://tmssl.akamaized.net//images/flagge/ver...,RC Strasbourg Alsace
2073,Patrice Covic,Attacking Midfield,17,-,0.0,right,Croatia,https://tmssl.akamaized.net//images/flagge/ver...,SV Werder Bremen
2139,Noah Jauny,Goalkeeper,20,"1,94m",0.0,right,Ireland,https://tmssl.akamaized.net//images/flagge/ver...,Stade Brestois 29
2196,Abdelhamid Ait Boudlal,Centre-Back,18,"1,90m",0.0,right,Morocco,https://tmssl.akamaized.net//images/flagge/ver...,Stade Rennais FC
2510,Lennart Koerdt,Attacking Midfield,20,"1,87m",0.0,right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,VfL Bochum
2524,David Odogu,Centre-Back,18,"1,91m",0.0,right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,VfL Wolfsburg

In [17]:
marketValueSixth = pd.DataFrame()
marketValueSixth["Market Value"] = marketValueFourth["Market Value"].str[1:-1]
marketValueSixth["Market Value"] = pd.to_numeric(marketValueSixth["Market Value"])

marketValueSixth

      Market Value
0              1.0
4              3.0
5              3.0
6              1.5
8              2.0
...            ...
2622           7.0
2623          50.0
2624          27.0
2625          22.0
2626           5.0

[2209 rows x 1 columns]

In [18]:
marketValueEleventh = pd.DataFrame()
marketValueEleventh["Market Value"] = marketValueFifth["Market Value"].str[1:-3]
marketValueEleventh["Market Value"] = pd.to_numeric(marketValueEleventh["Market Value"])

marketValueEleventh

Empty DataFrame
Columns: [Market Value]
Index: []

In [19]:
marketValueFourth.drop(columns=["Market Value"], inplace=True)
marketValueFifth.drop(columns=["Market Value"], inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\3646839043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marketValueFourth.drop(columns=["Market Value"], inplace=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\3646839043.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  marketValueFifth.drop(columns=["Market Value"], inplace=True)

In [20]:
marketValueTwelfth = pd.concat([marketValueFourth, marketValueSixth], axis=1)
marketValueThirteenth = pd.concat([marketValueFifth, marketValueEleventh], axis=1)

marketValueFourteenth = pd.concat([marketValueTwelfth, marketValueThirteenth], axis=0)

In [21]:
marketValueFourteenth

,Player,Position,Age,Height,Foot,Nation,Nation Flag Link,Team,Market Value
0,Kevin Müller,Goalkeeper,33,"1,90m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,1.0
4,Benedikt Gimber,Centre-Back,27,"1,87m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,3.0
5,Patrick Mainka,Centre-Back,30,"1,94m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,3.0
6,Tim Siersleben,Centre-Back,24,"1,87m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,1.5
8,Jonas Föhrenbach,Left-Back,28,"1,84m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,2.0
...,...,...,...,...,...,...,...,...,...
2622,Pablo Sarabia,Right Winger,32,"1,74m",left,Spain,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,7.0
2623,Matheus Cunha,Centre-Forward,25,"1,83m",right,Brazil,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,50.0
2624,Jørgen Strand Larsen,Centre-Forward,24,"1,93m",right,Norway,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,27.0
2625,Hee-chan Hwang,Centre-Forward,28,"1,77m",right,"Korea, South",https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,22.0
2626,Sasa Kalajdzic,Centre-Forward,27,"2,00m",right,Austria,https://tmssl.akamaized.net//images/flagge/ver...,Wolverhampton Wanderers,5.0

In [22]:
finalListPlayer = pd.concat(
    [marketValueTenth, marketValueFourteenth, listPlayer], axis=0
)
finalListPlayer = finalListPlayer.reset_index(drop=True)
finalListPlayer

,Player,Position,Age,Height,Foot,Nation,Nation Flag Link,Team,Market Value
0,Frank Feller,Goalkeeper,21,"1,83m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.3
1,Vitus Eicher,Goalkeeper,34,"1,91m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.2
2,Paul Tschernuth,Goalkeeper,23,"1,86m",left,Austria,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.1
3,Thomas Keller,Centre-Back,25,"1,86m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.3
4,Luka Janes,Defensive Midfield,21,"1,83m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,1.FC Heidenheim 1846,0.2
...,...,...,...,...,...,...,...,...,...
2623,Patrice Covic,Attacking Midfield,17,-,right,Croatia,https://tmssl.akamaized.net//images/flagge/ver...,SV Werder Bremen,0.0
2624,Noah Jauny,Goalkeeper,20,"1,94m",right,Ireland,https://tmssl.akamaized.net//images/flagge/ver...,Stade Brestois 29,0.0
2625,Abdelhamid Ait Boudlal,Centre-Back,18,"1,90m",right,Morocco,https://tmssl.akamaized.net//images/flagge/ver...,Stade Rennais FC,0.0
2626,Lennart Koerdt,Attacking Midfield,20,"1,87m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,VfL Bochum,0.0
2627,David Odogu,Centre-Back,18,"1,91m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,VfL Wolfsburg,0.0

In [23]:
listPlayerDetail = pd.DataFrame()
for li in finalListClub["Team Link 2"]:

    res = req.get(
        li,
        headers=headers,
    )
    sou = bs(res.content, "html.parser")
    tbl = sou.select_one('table:contains("PPG")')
    innerListPlayerDetail = pd.DataFrame(
        {
            "Player": [(i["title"]) for i in tbl.select("tbody td:nth-of-type(1) img")],
            "Position": [
                (i.text)
                for i in tbl.select("tbody td:nth-of-type(2) tr td:nth-of-type(1)")
            ][1::2],
            "Age": [(i.text) for i in tbl.select("tbody td:nth-of-type(3)")],
            "MP": [(i.text) for i in tbl.select("tbody td:nth-of-type(6)")],
            "Gls": [(i.text) for i in tbl.select("tbody td:nth-of-type(7)")],
            "Asts": [(i.text) for i in tbl.select("tbody td:nth-of-type(8)")],
            "YC": [(i.text) for i in tbl.select("tbody td:nth-of-type(9)")],
            "Second YC": [(i.text) for i in tbl.select("tbody td:nth-of-type(10)")],
            "RC": [(i.text) for i in tbl.select("tbody td:nth-of-type(11)")],
            "Subs On": [(i.text) for i in tbl.select("tbody td:nth-of-type(12)")],
            "Min": [(i.text) for i in tbl.select("tbody td:nth-of-type(15)")],
        }
    )

    teams = sou.find_all(
        class_="data-header__headline-wrapper data-header__headline-wrapper--oswald"
    )
    teamNameDetail = [team.get_text(strip=True) for team in teams]

    def addTeamNameDetail(c):
        c = teamNameDetail[0]
        return c

    innerListPlayerDetail["Team"] = innerListPlayerDetail.apply(
        addTeamNameDetail, axis=1
    )

    listPlayerDetail = pd.concat([listPlayerDetail, innerListPlayerDetail], axis=0)

c:\Users\Hp\Web Development\Portfolio\The-Score\venv\Lib\site-packages\soupsieve\css_parser.py:862: FutureWarning: The pseudo class ':contains' is deprecated, ':-soup-contains' should be used moving forward.
  warnings.warn(  # noqa: B028

In [24]:
listPlayerDetail = listPlayerDetail.reset_index(drop=True)
listPlayerDetail

,Player,Position,Age,MP,Gls,Asts,YC,Second YC,RC,Subs On,Min,Team
0,Kevin Müller,Goalkeeper,33,18,-,-,-,-,-,-,1.620',1.FC Heidenheim 1846
1,Frank Feller,Goalkeeper,21,Not used during this season,-,-,-,-,-,-,-,1.FC Heidenheim 1846
2,Vitus Eicher,Goalkeeper,34,Not used during this season,-,-,-,-,-,-,-,1.FC Heidenheim 1846
3,Paul Tschernuth,Goalkeeper,23,Not in squad during this season,-,-,-,-,-,-,-,1.FC Heidenheim 1846
4,Omar Traoré,Right-Back,26,15,-,1,3,-,-,-,1.294',1.FC Heidenheim 1846
...,...,...,...,...,...,...,...,...,...,...,...,...
3237,Sasa Kalajdzic,Centre-Forward,27,Not in squad during this season,-,-,-,-,-,-,-,Wolverhampton Wanderers
3238,Enso González,Left Winger,20,Not in squad during this season,-,-,-,-,-,-,-,Wolverhampton Wanderers
3239,Chiquinho,Left Winger,24,1,-,-,-,-,-,1,6',Wolverhampton Wanderers
3240,Nathan Fraser,Centre-Forward,19,Not in squad during this season,-,-,-,-,-,-,-,Wolverhampton Wanderers
3241,Tom Edozie,Right Winger,18,Not used during this season,-,-,-,-,-,-,-,Wolverhampton Wanderers

In [25]:
finalListPlayer["MP"] = ""
finalListPlayer["Gls"] = ""
finalListPlayer["Asts"] = ""
finalListPlayer["YC"] = ""
finalListPlayer["Second YC"] = ""
finalListPlayer["RC"] = ""
finalListPlayer["Subs On"] = ""
finalListPlayer["Min"] = ""
finalListPlayer["St"] = ""

for n in range(len(finalListPlayer["Player"])):
    for m in range(len(listPlayerDetail["Player"])):
        if ((finalListPlayer.loc[n, "Player"] == listPlayerDetail.loc[m, "Player"]) and (finalListPlayer.loc[n, "Position"] == listPlayerDetail.loc[m, "Position"]) and (finalListPlayer.loc[n, "Age"] == listPlayerDetail.loc[m, "Age"]) and (finalListPlayer.loc[n, "Team"] == listPlayerDetail.loc[m, "Team"])):
            finalListPlayer.loc[n, "MP"] = listPlayerDetail.loc[m, "MP"]
            finalListPlayer.loc[n, "Gls"] = listPlayerDetail.loc[m, "Gls"]
            finalListPlayer.loc[n, "Asts"] = listPlayerDetail.loc[m, "Asts"]
            finalListPlayer.loc[n, "YC"] = listPlayerDetail.loc[m, "YC"]
            finalListPlayer.loc[n, "Second YC"] = listPlayerDetail.loc[m, "Second YC"]
            finalListPlayer.loc[n, "RC"] = listPlayerDetail.loc[m, "RC"]
            finalListPlayer.loc[n, "Subs On"] = listPlayerDetail.loc[m, "Subs On"]
            finalListPlayer.loc[n, "Min"] = listPlayerDetail.loc[m, "Min"]

In [26]:
uniqueValues = finalListPlayer["MP"].unique()
uniqueValues

array(['Not used during this season', 'Not in squad during this season',
       '1', '8', '4', '14', '13', '9', '6', '3', '5', '7', '16', '2',
       '11', '17', '10', '15', '19', '18', '12', '20', '21', '22'],
      dtype=object)

In [27]:
finalListPlayerFoot = finalListPlayer[finalListPlayer["Foot"].str.contains("\xa0")]
finalListPlayer.drop(
    finalListPlayer[finalListPlayer["Foot"].str.contains("\xa0")].index,
    inplace=True,
)
finalListPlayerFoot["Foot"] = finalListPlayerFoot["Foot"].str[:-10]

finalListPlayer = pd.concat([finalListPlayer, finalListPlayerFoot], axis=0)

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\1422069622.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFoot["Foot"] = finalListPlayerFoot["Foot"].str[:-10]

In [28]:
finalListPlayer["MP"] = finalListPlayer["MP"].replace("Not used during this season", 0)
finalListPlayer["MP"] = finalListPlayer["MP"].replace("Not in squad during this season", 0)
finalListPlayer["MP"] = finalListPlayer["MP"].replace("", 0)
finalListPlayer["Gls"] = finalListPlayer["Gls"].replace("-", 0)
finalListPlayer["Gls"] = finalListPlayer["Gls"].replace("", 0)
finalListPlayer["Asts"] = finalListPlayer["Asts"].replace("-", 0)
finalListPlayer["Asts"] = finalListPlayer["Asts"].replace("", 0)
finalListPlayer["YC"] = finalListPlayer["YC"].replace("-", 0)
finalListPlayer["YC"] = finalListPlayer["YC"].replace("", 0)
finalListPlayer["Second YC"] = finalListPlayer["Second YC"].replace("-", 0)
finalListPlayer["Second YC"] = finalListPlayer["Second YC"].replace("", 0)
finalListPlayer["RC"] = finalListPlayer["RC"].replace("-", 0)
finalListPlayer["RC"] = finalListPlayer["RC"].replace("", 0)
finalListPlayer["Subs On"] = finalListPlayer["Subs On"].replace("-", 0)
finalListPlayer["Subs On"] = finalListPlayer["Subs On"].replace("", 0)
finalListPlayer["Min"] = finalListPlayer["Min"].replace("-", 0)
finalListPlayer["Min"] = finalListPlayer["Min"].replace("", 0)
finalListPlayer["St"] = finalListPlayer["St"].replace("-", 0)
finalListPlayer["St"] = finalListPlayer["St"].replace("", 0)
finalListPlayer["Position"] = finalListPlayer["Position"].replace("", "-")
finalListPlayer["Age"] = finalListPlayer["Age"].replace("", "-")
finalListPlayer["Height"] = finalListPlayer["Height"].replace("", "-")
finalListPlayer["Foot"] = finalListPlayer["Foot"].replace("", "-")
finalListPlayer["Nation"] = finalListPlayer["Nation"].replace("", "-")

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\1401895066.py:19: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  finalListPlayer["St"] = finalListPlayer["St"].replace("", 0)

In [29]:
finalListPlayer["MP"] = finalListPlayer["MP"].astype(int)
finalListPlayer["Subs On"] = finalListPlayer["Subs On"].astype(int)

finalListPlayer["St"] = finalListPlayer["MP"].sub(finalListPlayer["Subs On"], fill_value=0)

In [30]:
uniquePositions = finalListPlayer["Position"].unique()
uniquePositions

array(['Goalkeeper', 'Centre-Back', 'Defensive Midfield',
       'Centre-Forward', 'Right-Back', 'Left Winger',
       'Attacking Midfield', 'Central Midfield', 'Right Winger',
       'Left-Back', 'Right Midfield', 'Left Midfield', 'Second Striker'],
      dtype=object)

In [31]:
finalListPlayer["Position"] = finalListPlayer["Position"].replace("Goalkeeper", "GK")
finalListPlayer["Position"] = finalListPlayer["Position"].replace(
    ["Centre-Back", "Left-Back", "Right-Back"], "DF"
)
finalListPlayer["Position"] = finalListPlayer["Position"].replace(
    [
        "Defensive Midfield",
        "Central Midfield",
        "Right Midfield",
        "Left Midfield",
        "Attacking Midfield",
    ],
    "MF",
)
finalListPlayer["Position"] = finalListPlayer["Position"].replace(
    ["Centre-Forward", "Left Winger", "Right Winger", "Second Striker"], "FW"
)

In [32]:
finalListPlayer["Mini Team Crest"] = ""
finalListPlayer["Big Team Crest"] = ""
finalListPlayer["League"] = ""
finalListPlayer["Team Link"] = ""
finalListPlayer["Team Link 2"] = ""

for p in range(len(finalListPlayer["Team"])):
    for r in range(len(finalListClub["Team"])):
        if finalListPlayer.loc[p, "Team"] == finalListClub.loc[r, "Team"]:
            finalListPlayer.loc[p, "Mini Team Crest"] = finalListClub.loc[r, "Mini Team Crest"]
            finalListPlayer.loc[p, "Big Team Crest"] = finalListClub.loc[r, "Big Team Crest"]
            finalListPlayer.loc[p, "League"] = finalListClub.loc[r, "League"]
            finalListPlayer.loc[p, "Team Link"] = finalListClub.loc[r, "Team Link"]
            finalListPlayer.loc[p, "Team Link 2"] = finalListClub.loc[r, "Team Link 2"]

In [33]:
finalListPlayerMin = finalListPlayer[finalListPlayer["Min"] == 0]
finalListPlayer.drop(
    finalListPlayer[finalListPlayer["Min"] == 0].index,
    inplace=True,
)

finalListPlayer["Min"] = finalListPlayer["Min"].str.replace(".", "")
finalListPlayer["Min"] = finalListPlayer["Min"].str[:-1]
finalListPlayer["Min"] = finalListPlayer["Min"].astype(int)

In [34]:
finalListPlayer = pd.concat([finalListPlayer, finalListPlayerMin], axis=0)

In [35]:
finalListPlayer = finalListPlayer.sort_values(by="Team")
finalListPlayer = finalListPlayer.reset_index(drop=True)

In [36]:
finalListPlayer.insert(10, "St", finalListPlayer.pop("St"))
finalListPlayer.insert(7, "League", finalListPlayer.pop("League"))

In [37]:
finalListClub.insert(10, "Pts/MP", finalListClub.pop("Pts/MP"))
finalListClub.insert(12, "Team Link", finalListClub.pop("Team Link"))
finalListClub.insert(13, "Mini Team Crest", finalListClub.pop("Mini Team Crest"))
finalListClub.insert(13, "Big Team Crest", finalListClub.pop("Big Team Crest"))

finalListClub = finalListClub.sort_values(by="Pts/MP", ascending=False)
finalListClub = finalListClub.reset_index(drop=True)

In [38]:
response = req.get(
    "https://flagpedia.net/index",
    headers=headers,
)
soup = bs(response.content, "html.parser")
table = soup.find("ul", class_="flag-grid")
flagList = pd.DataFrame(
    {
        "Flag": [(i.text) for i in table.select("li a")],
        "Flag Link": [("https://flagpedia.net" + i["href"]) for i in table.select("li a")],
    }
)

In [39]:
flagList["Flag"] = flagList["Flag"].str.replace("\n\n", "")
flagList["Flag"] = flagList["Flag"].str.replace("\n", "")

In [40]:
flagListCode = pd.DataFrame()
for nationCode in flagList["Flag Link"]:
    responseSecond = req.get(
        nationCode,
        headers=headers,
    )
    soupSecond = bs(responseSecond.content, "html.parser")
    tableSecond = soupSecond.find("table", class_="table-dl")
    flagCode = pd.DataFrame(
        {
            "Flag Code": [(i.text) for i in tableSecond.select("tbody tr:nth-of-type(2) td")],
        }
    )

    flagListCode = pd.concat([flagListCode, flagCode], axis=0)

In [41]:
flagListCode = flagListCode.reset_index(drop=True)
flagListCodeOther = flagListCode["Flag Code"].str.split(",", expand=True)

In [42]:
flagListCode = pd.concat([flagListCode, flagListCodeOther], axis=1)

In [43]:
flagListCode.rename(columns={0: "Flag Code 1", 1: "Flag Code 2"}, inplace=True)
flagListCode["Flag Code 2"] = flagListCode["Flag Code 2"].str[:-13]

In [44]:
flagList = pd.concat([flagList, flagListCode], axis=1)

In [45]:
flagListFiltered = flagList[flagList["Flag Code 1"].str.contains("(ISO 3166-2:GB)")]
flagList.drop(
    flagList[flagList["Flag Code 1"].str.contains("(ISO 3166-2:GB)")].index,
    inplace=True,
)

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\453612881.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  flagListFiltered = flagList[flagList["Flag Code 1"].str.contains("(ISO 3166-2:GB)")]
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\453612881.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  flagList[flagList["Flag Code 1"].str.contains("(ISO 3166-2:GB)")].index,

In [46]:
flagListFiltered["Flag Code 1"] = flagListFiltered["Flag Code 1"].str[:-16]
flagListFiltered

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\693478608.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flagListFiltered["Flag Code 1"] = flagListFiltered["Flag Code 1"].str[:-16]

,Flag,Flag Link,Flag Code,Flag Code 1,Flag Code 2
67,England,https://flagpedia.net/england,GB-ENG (ISO 3166-2:GB),GB-ENG,None
166,Northern Ireland,https://flagpedia.net/northern-ireland,GB-NIR (ISO 3166-2:GB),GB-NIR,None
198,Scotland,https://flagpedia.net/scotland,GB-SCT (ISO 3166-2:GB),GB-SCT,None
248,Wales,https://flagpedia.net/wales,GB-WLS (ISO 3166-2:GB),GB-WLS,None

In [47]:
flagList = pd.concat([flagList, flagListFiltered], axis=0)
flagList = flagList.reset_index(drop=True)

In [48]:
nationCodes = [
    "GB-ENG",
    "ES",
    "FR",
    "DE",
    "IT",
]

for l in range(len(finalListClub["League"])):
    if finalListClub.loc[l, "League"] == "EPL":
        finalListClub.loc[l, "Nation Flag Code"] = "GB-ENG"
    elif finalListClub.loc[l, "League"] == "La Liga":
        finalListClub.loc[l, "Nation Flag Code"] = "ES"
    elif finalListClub.loc[l, "League"] == "Ligue 1":
        finalListClub.loc[l, "Nation Flag Code"] = "FR"
    elif finalListClub.loc[l, "League"] == "Bundesliga":
        finalListClub.loc[l, "Nation Flag Code"] = "DE"
    elif finalListClub.loc[l, "League"] == "Serie A":
        finalListClub.loc[l, "Nation Flag Code"] = "IT"

In [49]:
for n in range(len(finalListPlayer["Nation"])):
    for f in range(len(flagList["Flag"])):
        if finalListPlayer.loc[n, "Nation"] == flagList.loc[f, "Flag"]:
            finalListPlayer.loc[n, "Flag Code"] = flagList.loc[f, "Flag Code 1"]

In [50]:
finalListPlayerFiltered = finalListPlayer[finalListPlayer["Flag Code"].isna()]
finalListPlayer.drop(
    finalListPlayer[finalListPlayer["Flag Code"].isna()].index,
    inplace=True,
)
finalListPlayerFiltered[["Player", "Nation", "Flag Code"]]

                      Player              Nation Flag Code
30           Woo-yeong Jeong        Korea, South       NaN
68            Hyun-seok Hong        Korea, South       NaN
69              Jae-sung Lee        Korea, South       NaN
112   Jean-Daniel Akpa Akpro       Cote d'Ivoire       NaN
123             Milan Djuric  Bosnia-Herzegovina       NaN
...                      ...                 ...       ...
2567             Eric Bailly       Cote d'Ivoire       NaN
2587            Tomas Soucek      Czech Republic       NaN
2594         Vladimír Coufal      Czech Republic       NaN
2615        Emmanuel Agbadou       Cote d'Ivoire       NaN
2627          Hee-chan Hwang        Korea, South       NaN

[102 rows x 3 columns]

In [51]:
uniqueNations = finalListPlayerFiltered["Nation"].unique()
uniqueNations

array(['Korea, South', "Cote d'Ivoire", 'Bosnia-Herzegovina', 'Türkiye',
       'Congo', 'Czech Republic', 'The Gambia'], dtype=object)

In [52]:
finalListPlayerFilteredCongo = finalListPlayerFiltered[finalListPlayerFiltered["Nation"] == "Congo"]
finalListPlayerFilteredCongo

,Player,Position,Age,Height,Foot,Nation,Nation Flag Link,League,Team,Market Value,...,YC,Second YC,RC,Subs On,Min,Mini Team Crest,Big Team Crest,Team Link,Team Link 2,Flag Code
310,Melvin Zinga,GK,22,"1,87m",left,Congo,https://tmssl.akamaized.net//images/flagge/ver...,Ligue 1,Angers SCO,0.1,...,0,0,0,0,0,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/sco-angers/kader...,https://www.transfermarkt.com/sco-angers/leist...,NaN
702,Antoine Makoumbou,MF,26,"1,87m",right,Congo,https://tmssl.akamaized.net//images/flagge/ver...,Serie A,Cagliari Calcio,4.0,...,0,1,0,2,1145,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/cagliari-calcio/...,https://www.transfermarkt.com/cagliari-calcio/...,NaN
1715,Gabriel Charpentier,FW,25,"1,88m",right,Congo,https://tmssl.akamaized.net//images/flagge/ver...,Serie A,Parma Calcio 1913,1.6,...,1,0,0,10,264,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/parma-calcio-191...,https://www.transfermarkt.com/parma-calcio-191...,NaN

In [53]:
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Korea, South", "South Korea")
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Cote d'Ivoire", "Côte d'Ivoire")
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Bosnia-Herzegovina", "Bosnia and Herzegovina")
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Türkiye", "Turkey")
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Congo", "Republic of the Congo")
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Czech Republic", "Czechia")
finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("The Gambia", "Gambia")

C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Korea, South", "South Korea")
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Cote d'Ivoire", "Côte d'Ivoire")
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Bosnia-Herzegovina", "Bosnia and Herzegovina")
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Türkiye", "Turkey")
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Congo", "Republic of the Congo")
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("Czech Republic", "Czechia")
C:\Users\Hp\AppData\Local\Temp\ipykernel_13336\2693570354.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  finalListPlayerFiltered["Nation"] = finalListPlayerFiltered["Nation"].str.replace("The Gambia", "Gambia")

In [54]:
finalListPlayerFiltered = finalListPlayerFiltered.reset_index(drop=True)

for n in range(len(finalListPlayerFiltered["Nation"])):
    for f in range(len(flagList["Flag"])):
        if finalListPlayerFiltered.loc[n, "Nation"] == flagList.loc[f, "Flag"]:
            finalListPlayerFiltered.loc[n, "Flag Code"] = flagList.loc[f, "Flag Code 1"]

finalListPlayerFiltered

,Player,Position,Age,Height,Foot,Nation,Nation Flag Link,League,Team,Market Value,...,YC,Second YC,RC,Subs On,Min,Mini Team Crest,Big Team Crest,Team Link,Team Link 2,Flag Code
0,Woo-yeong Jeong,MF,25,"1,79m",right,South Korea,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FC Union Berlin,4.0,...,2,0,0,4,832,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fc-union-berli...,https://www.transfermarkt.com/1-fc-union-berli...,KR
1,Hyun-seok Hong,MF,25,"1,77m",left,South Korea,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FSV Mainz 05,5.0,...,0,0,0,11,387,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fsv-mainz-05/k...,https://www.transfermarkt.com/1-fsv-mainz-05/l...,KR
2,Jae-sung Lee,MF,32,"1,80m",left,South Korea,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FSV Mainz 05,2.5,...,2,0,0,0,1429,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fsv-mainz-05/k...,https://www.transfermarkt.com/1-fsv-mainz-05/l...,KR
3,Jean-Daniel Akpa Akpro,MF,32,"1,80m",right,Côte d'Ivoire,https://tmssl.akamaized.net//images/flagge/ver...,Serie A,AC Monza,0.5,...,1,0,0,1,185,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/ac-monza/kader/v...,https://www.transfermarkt.com/ac-monza/leistun...,CI
4,Milan Djuric,FW,34,"1,99m",right,Bosnia and Herzegovina,https://tmssl.akamaized.net//images/flagge/ver...,Serie A,AC Monza,1.5,...,3,0,0,5,1271,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/ac-monza/kader/v...,https://www.transfermarkt.com/ac-monza/leistun...,BA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Eric Bailly,DF,30,"1,87m",right,Côte d'Ivoire,https://tmssl.akamaized.net//images/flagge/ver...,La Liga,Villarreal CF,2.5,...,2,0,0,2,579,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/fc-villarreal/ka...,https://www.transfermarkt.com/fc-villarreal/le...,CI
98,Tomas Soucek,MF,29,"1,92m",right,Czechia,https://tmssl.akamaized.net//images/flagge/ver...,EPL,West Ham United,24.0,...,6,0,0,3,1526,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/west-ham-united/...,https://www.transfermarkt.com/west-ham-united/...,CZ
99,Vladimír Coufal,DF,32,"1,74m",right,Czechia,https://tmssl.akamaized.net//images/flagge/ver...,EPL,West Ham United,7.0,...,2,0,0,7,571,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/west-ham-united/...,https://www.transfermarkt.com/west-ham-united/...,CZ
100,Emmanuel Agbadou,DF,27,"1,92m",right,Côte d'Ivoire,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,10.0,...,1,0,0,0,180,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,CI
101,Hee-chan Hwang,FW,28,"1,77m",right,South Korea,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,22.0,...,0,0,0,10,543,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,KR

In [55]:
finalListPlayer = pd.concat([finalListPlayer, finalListPlayerFiltered], axis=0)

finalListPlayer = finalListPlayer.sort_values(by="Team")
finalListPlayer = finalListPlayer.reset_index(drop=True)

finalListPlayer

,Player,Position,Age,Height,Foot,Nation,Nation Flag Link,League,Team,Market Value,...,YC,Second YC,RC,Subs On,Min,Mini Team Crest,Big Team Crest,Team Link,Team Link 2,Flag Code
0,Thomas Keller,DF,25,"1,86m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FC Heidenheim 1846,0.3,...,1,0,0,0,60,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fc-heidenheim-...,https://www.transfermarkt.com/1-fc-heidenheim-...,DE
1,Sirlord Conteh,FW,28,"1,78m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FC Heidenheim 1846,1.5,...,1,0,0,16,461,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fc-heidenheim-...,https://www.transfermarkt.com/1-fc-heidenheim-...,DE
2,Paul Wanner,MF,19,"1,85m",left,Germany,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FC Heidenheim 1846,18.0,...,2,0,0,2,1257,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fc-heidenheim-...,https://www.transfermarkt.com/1-fc-heidenheim-...,DE
3,Adrian Beck,MF,27,"1,86m",right,Germany,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FC Heidenheim 1846,2.0,...,0,0,0,11,499,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fc-heidenheim-...,https://www.transfermarkt.com/1-fc-heidenheim-...,DE
4,Leo Scienza,FW,26,"1,75m",both,Brazil,https://tmssl.akamaized.net//images/flagge/ver...,Bundesliga,1.FC Heidenheim 1846,3.0,...,0,0,0,5,825,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/1-fc-heidenheim-...,https://www.transfermarkt.com/1-fc-heidenheim-...,BR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2623,André,MF,23,"1,76m",right,Brazil,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,25.0,...,3,0,0,2,1142,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,BR
2624,Mario Lemina,MF,31,"1,84m",right,Gabon,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,9.0,...,3,0,0,2,1363,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,GA
2625,Jean-Ricner Bellegarde,MF,26,"1,72m",right,France,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,18.0,...,3,0,0,10,846,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,FR
2626,Rodrigo Gomes,MF,21,"1,75m",right,Portugal,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,15.0,...,0,0,0,9,543,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,PT
2627,Hee-chan Hwang,FW,28,"1,77m",right,South Korea,https://tmssl.akamaized.net//images/flagge/ver...,EPL,Wolverhampton Wanderers,22.0,...,0,0,0,10,543,https://tmssl.akamaized.net//images/wappen/tin...,https://tmssl.akamaized.net//images/wappen/hea...,https://www.transfermarkt.com/wolverhampton-wa...,https://www.transfermarkt.com/wolverhampton-wa...,KR

In [56]:
nanCountsPlayer = finalListPlayer.isna().sum()
print(nanCountsPlayer)

Player              0
Position            0
Age                 0
Height              0
Foot                0
Nation              0
Nation Flag Link    0
League              0
Team                0
Market Value        0
MP                  0
St                  0
Gls                 0
Asts                0
YC                  0
Second YC           0
RC                  0
Subs On             0
Min                 0
Mini Team Crest     0
Big Team Crest      0
Team Link           0
Team Link 2         0
Flag Code           0
dtype: int64

In [57]:
nanCountsClub = finalListClub.isna().sum()
print(nanCountsClub)

Team                0
MP                  0
W                   0
D                   0
L                   0
Goals               0
+/-                 0
Pts/MP              0
Pts                 0
League              0
Team Link           0
Team Link 2         0
Mini Team Crest     0
Big Team Crest      0
Nation Flag Code    0
dtype: int64

In [58]:
import json
import shutil
import os

dataClub = finalListClub.to_dict(orient='records')
dataClubList = []
dataClubList.append(dataClub)
dataPlayer = finalListPlayer.to_dict(orient='records')
dataPlayerList = []
dataPlayerList.append(dataPlayer)
data = dataClubList + dataPlayerList

with open('data.json', 'w') as f:
    json.dump(data, f)

source_path = 'data.json'
destination_path = os.path.join('src', 'data', 'data.json')

if os.path.exists(source_path):
    shutil.copy(source_path, destination_path)
    print(f"Successfully copied {source_path} to {destination_path}")
else:
    print("Source file does not exist!")

Successfully copied data.json to src\data\data.json